services:
  butterfly-ai-php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: butterfly-ai-php
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - nex-academy_nex-network   # attach to existing network
    environment:
      - DB_HOST=nex-mysql
      - DB_PORT=3306
      - DB_DATABASE=butterfly-ai
      - DB_USERNAME=root
      - DB_PASSWORD=

  butterfly-ai-nginx:
    image: nginx:alpine
    container_name: butterfly-ai-nginx
    ports:
      - "8026:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - nex-academy_nex-network   # attach to existing network
    depends_on:
      - butterfly-ai-php

networks:
  nex-academy_nex-network:
    external: true   # tell compose to use the already existing network
